[package]
name = "pdfium_rs"
version = "0.1.0"
authors = ["Andrew Safigan <asafigan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdfium_bindings = { path = "crates/pdfium_bindings", version = "0.1.0" }

once_cell = "1"

[dev-dependencies]
image = "0.23"

[workspace]
members = ["crates/*"]
